const fs=require('fs');
const path='/home/ubuntu/hokcoach/data/source_seeds/youtube/seed_manifest.json';
const d=JSON.parse(fs.readFileSync(path,'utf8'));
const rows=[
['JXA8hIqofgc','top-ranked Yu Ji marksman with 2300 points','虞姬'],['jD9NcP8e5Ls','Marksman Di Renjie strategy in a losing game','狄仁杰'],['Gu02NlzwwYA','元射显微级教学8大盲区技巧','元射'],['Dvtdc_G-g0s','Why is it hard for you to rank up as a marksman','射手'],['nXQdkgdUCeI','虞姬突破1800到2100全局思路','虞姬'],['PgPq6M2MJOg','Season 42 Development Lane Tier Rankings','射手'],['Bhy2tuYTZ0I','元射突破1700到2100全局思路','元射'],['eMQnmilhUIo','虞姬省标小国前中后期全局思路','虞姬'],['UOWtFPj-35A','Sun Shangxiang marksman value training','孙尚香'],['j6V2tFR1am0','mid-lane 85-rank mage plays marksman','射手'],['PRkkfUNHS2E','marksmen and junglers basic skills','射手'],['_Hx2nRuGhpI','1897 peak-ranking marksman loses in Diamond','射手'],['vhKMr8qoQ1Q','Do not play marksman if not ruthless','射手'],['HhJbqZH6vZ8','70-rank marksman breaks through to Diamond','射手'],['wLlmQH9MyaQ','top-tier marksman team-fight strategy','射手'],['OWkKGu_I6KM','90 rating 49 win-rate marksman replay','射手'],['qKmVaoX6mp4','一诺超神法球流艾琳完美补刀极致走位','艾琳'],['YV9M2O8WqR8','three items behind marksman difficulty','射手'],['ZmaF338k6Js','Yuanliu marksman teamfight positioning','元射'],['F20X22kruGc','new stealth item marksman analysis','射手'],['60R-zczvYTU','Sun Quan formulaic speedrun to 2100 marksman guide','孙权'],['aRTUp7kRrgg','伽罗逆风翻盘率射手','伽罗'],['m6kggiDMFVI','后羿射手打法','后羿'],['VlUABEmNWvE','孙尚香突破1800到2100全局思路','孙尚香'],['yF37fT4TD_k','后羿巅峰1800发育路','后羿'],['l4K7AmkaCFU','鲁班逆风放塔1800分巅峰赛','鲁班'],['rlNAY6dpPYg','虞姬射手中期节奏与后期掉点','虞姬'],['uNoD1Cfpqww','low-elo marksman climb guide','射手'],['W3ibfGMw_0Y','3分钟单杀3次的射手12分钟送掉比赛','射手']
];
const seen=new Set(d.records.map(r=>r.video_id));
for(const [id,title,hero] of rows) if(!seen.has(id)) d.records.push({seed_id:`hokclass_${String(d.records.length+1).padStart(3,'0')}`,video_id:id,url:`https://www.youtube.com/watch?v=${id}`,title_hint:title,title,role_hint:'射手',role:'射手',hero,source_channel:'HonorofKings王者提升班',source_kind:'channel role-search',transcript_status:'pending',download_status:'pending',metadata_status:'search-verified',evidence_quality:'search-verified',rank_stratum:'待确认',rank_evidence:'needs-title-or-thumbnail-verification',series:'其他',coverage_status:'needs-verification'});
d.count=d.records.length;
fs.writeFileSync(path,JSON.stringify(d,null,2)+'\n');
console.log(d.count);
